name: "@akaoio/air"
description: "Distributed P2P database system with Stacker framework integration"
version: "2.1.0"
author: "AKAO Team"
repository: "https://github.com/akaoio/air"
license: "MIT"
tagline: "Distributed P2P database with Manager-powered system management"
foundation: "Built on GUN distributed database with Stacker framework for system-wide orchestration"